version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  create_cohorts:
    run: stata-mp:latest analysis/000_define_covariates.do
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        log1: logs/start_create_analysis_dataset.smcl 
        data1: output/data/file_imid.dta
        data2: output/data/file_joint.dta
        data3: output/data/file_skin.dta
        data4: output/data/file_bowel.dta
        data5: output/data/file_imiddrugcategory.dta
        data6: output/data/file_standtnf.dta
        data7: output/data/file_standtnf3m.dta
        data8: output/data/file_tnfmono.dta
        data9: output/data/file_standil6.dta
        data10: output/data/file_standil17.dta
        data11: output/data/file_standil23.dta
        data12: output/data/file_standjaki.dta
        data13: output/data/file_standritux.dta

  run_baseline_tables:
    run: stata-mp:latest analysis/100_baseline_characteristics.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log2: logs/descriptive_tables.smcl 
      
  run_cox_models_imid:
    run: stata-mp:latest analysis/201_cox_models.do "imid"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log3: logs/cox_models_imid.smcl 
        data14: output/data/cox_model_summary_imid.dta
        
  run_cox_models_joint:
    run: stata-mp:latest analysis/201_cox_models.do "joint"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log4: logs/cox_models_joint.smcl 
        data15: output/data/cox_model_summary_joint.dta

  run_cox_models_skin:
    run: stata-mp:latest analysis/201_cox_models.do "skin"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log5: logs/cox_models_skin.smcl 
        data16: output/data/cox_model_summary_skin.dta
 
  run_cox_models_bowel:
    run: stata-mp:latest analysis/201_cox_models.do "bowel"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log6: logs/cox_models_bowel.smcl 
        data17: output/data/cox_model_summary_bowel.dta
 
  run_cox_models_imiddrugcategory:
    run: stata-mp:latest analysis/201_cox_models.do "imiddrugcategory"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log7: logs/cox_models_imiddrugcategory.smcl 
        data18: output/data/cox_model_summary_imiddrugcategory.dta
  
  run_cox_models_standtnf:
    run: stata-mp:latest analysis/201_cox_models.do "standtnf"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log8: logs/cox_models_standtnf.smcl 
        data19: output/data/cox_model_summary_standtnf.dta

  run_cox_models_standtnf3m:
    run: stata-mp:latest analysis/201_cox_models.do "standtnf3m"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log9: logs/cox_models_standtnf3m.smcl 
        data20: output/data/cox_model_summary_standtnf3m.dta
       
  run_cox_models_tnfmono:
    run: stata-mp:latest analysis/201_cox_models.do "tnfmono"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log10: logs/cox_models_tnfmono.smcl 
        data21: output/data/cox_model_summary_tnfmono.dta
  
  run_cox_models_standil6:
    run: stata-mp:latest analysis/201_cox_models.do "standil6"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log11: logs/cox_models_standil6.smcl 
        data22: output/data/cox_model_summary_standil6.dta
  
  run_cox_models_standil17:
    run: stata-mp:latest analysis/201_cox_models.do "standil17"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log12: logs/cox_models_standil17.smcl 
        data23: output/data/cox_model_summary_standil17.dta
 
  run_cox_models_standil23:
    run: stata-mp:latest analysis/201_cox_models.do "standil23"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log13: logs/cox_models_standil23.smcl 
        data24: output/data/cox_model_summary_standil23.dta
 
  run_cox_models_standjaki:
    run: stata-mp:latest analysis/201_cox_models.do "standjaki"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log14: logs/cox_models_standjaki.smcl 
        data25: output/data/cox_model_summary_standjaki.dta
  
  run_cox_models_standritux:
    run: stata-mp:latest analysis/201_cox_models.do "standritux"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log15: logs/cox_models_standritux.smcl 
        data26: output/data/cox_model_summary_standritux.dta
  
  run_survival_curves:
    run: stata-mp:latest analysis/301_survival_curves.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log16: logs/graphs.smcl 
        figure1: output/figures/survcurv_imiddrugcategory_icu.svg
        figure2: output/figures/imiddrugcategory_graph.gph        figure3: output/figures/survcurv_imiddrugcategory_died.svg
        figure4: output/figures/survcurv_bowel_icu.svg
        figure5: output/figures/bowel_graph.gph
        figure6: output/figures/survcurv_bowel_died.svg
        figure7: output/figures/survcurv_skin_icu.svg
        figure8: output/figures/skin_graph.gph
        figure9: output/figures/survcurv_skin_died.svg
        figure10: output/figures/survcurv_joint_icu.svg
        figure11: output/figures/joint_graph.gph
        figure12: output/figures/survcurv_joint_died.svg
        figure13: output/figures/survcurv_imid_icu.svg
        figure14: output/figures/imid_graph.gph
        figure15: output/figures/survcurv_imid_died.svg

  run_outcomes_check:
    run: r:latest analysis/outcomes_check_withandwithoutpositivetest.R
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        data27: output/data/outcomes_check.csv 

        