version: '3.0'

expectations:
  population_size: 50000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  create_cohorts:
    run: stata-mp:latest analysis/000_define_covariates.do
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        log1: logs/start_create_analysis_dataset.smcl 
        data1: output/data/file_imid.dta
        data2: output/data/file_joint.dta
        data3: output/data/file_skin.dta
        data4: output/data/file_bowel.dta
        data5: output/data/file_imiddrugcategory.dta
        data6: output/data/file_standtnf.dta
        data7: output/data/file_standtnf3m.dta
        data8: output/data/file_tnfmono.dta
        data9: output/data/file_standil6.dta
        data10: output/data/file_standil17.dta
        data11: output/data/file_standil23.dta
        data12: output/data/file_standjaki.dta
        data13: output/data/file_standritux.dta
        data14: output/data/file_standinflix.dta

  run_baseline_tables:
    run: stata-mp:latest analysis/100_baseline_characteristics.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/descriptive_tables.smcl 
      
  run_cox_models_imid:
    run: stata-mp:latest analysis/202_cox_models.do "imid"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_imid.smcl 
        data1: output/data/cox_model_summary_imid.dta
        data2: output/data/cox_model_summary_haemonc_imid.dta
        
  run_cox_models_joint:
    run: stata-mp:latest analysis/202_cox_models.do "joint"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_joint.smcl 
        data1: output/data/cox_model_summary_joint.dta
        data2: output/data/cox_model_summary_haemonc_joint.dta

  run_cox_models_skin:
    run: stata-mp:latest analysis/202_cox_models.do "skin"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_skin.smcl 
        data1: output/data/cox_model_summary_skin.dta
        data2: output/data/cox_model_summary_haemonc_skin.dta
 
  run_cox_models_bowel:
    run: stata-mp:latest analysis/202_cox_models.do "bowel"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_bowel.smcl 
        data1: output/data/cox_model_summary_bowel.dta
        data2: output/data/cox_model_summary_haemonc_bowel.dta
 
  run_cox_models_imiddrugcategory:
    run: stata-mp:latest analysis/202_cox_models.do "imiddrugcategory"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_imiddrugcategory.smcl 
        data1: output/data/cox_model_summary_imiddrugcategory.dta
        data2: output/data/cox_model_summary_haemonc_imiddrugcategory.dta
  
  run_cox_models_standtnf:
    run: stata-mp:latest analysis/202_cox_models.do "standtnf"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_standtnf.smcl 
        data1: output/data/cox_model_summary_standtnf.dta
        data2: output/data/cox_model_summary_haemonc_standtnf.dta

  run_cox_models_standtnf3m:
    run: stata-mp:latest analysis/202_cox_models.do "standtnf3m"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_standtnf3m.smcl 
        data1: output/data/cox_model_summary_standtnf3m.dta
        data2: output/data/cox_model_summary_haemonc_standtnf3m.dta
       
  run_cox_models_tnfmono:
    run: stata-mp:latest analysis/202_cox_models.do "tnfmono"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_tnfmono.smcl 
        data1: output/data/cox_model_summary_tnfmono.dta
        data2: output/data/cox_model_summary_haemonc_tnfmono.dta
  
  run_cox_models_standil6:
    run: stata-mp:latest analysis/202_cox_models.do "standil6"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_standil6.smcl 
        data1: output/data/cox_model_summary_standil6.dta
        data2: output/data/cox_model_summary_haemonc_standil6.dta
  
  run_cox_models_standil17:
    run: stata-mp:latest analysis/202_cox_models.do "standil17"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_standil17.smcl 
        data1: output/data/cox_model_summary_standil17.dta
        data2: output/data/cox_model_summary_haemonc_standil17.dta
 
  run_cox_models_standil23:
    run: stata-mp:latest analysis/202_cox_models.do "standil23"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_standil23.smcl 
        data1: output/data/cox_model_summary_standil23.dta
        data2: output/data/cox_model_summary_haemonc_standil23.dta
 
  run_cox_models_standjaki:
    run: stata-mp:latest analysis/202_cox_models.do "standjaki"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_standjaki.smcl 
        data1: output/data/cox_model_summary_standjaki.dta
        data2: output/data/cox_model_summary_haemonc_standjaki.dta
  
  run_cox_models_standritux:
    run: stata-mp:latest analysis/202_cox_models.do "standritux"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_standritux.smcl 
        data1: output/data/cox_model_summary_standritux.dta
        data2: output/data/cox_model_summary_haemonc_standritux.dta
        
  run_cox_models_standinflix:
    run: stata-mp:latest analysis/202_cox_models.do "standinflix"
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/cox_models_standinflix.smcl 
        data1: output/data/cox_model_summary_standinflix.dta
        data2: output/data/cox_model_summary_haemonc_standinflix.dta
  
  run_survival_curves:
    run: stata-mp:latest analysis/301_survival_curves.do
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        log1: logs/graphs.smcl 
        figure1: output/figures/survcurv_imiddrugcategory_icuordeath.svg
        figure2: output/figures/imiddrugcategory_graph.gph
        figure3: output/figures/survcurv_imiddrugcategory_died.svg
        figure4: output/figures/survcurv_bowel_icuordeath.svg
        figure5: output/figures/bowel_graph.gph
        figure6: output/figures/survcurv_bowel_died.svg
        figure7: output/figures/survcurv_skin_icuordeath.svg
        figure8: output/figures/skin_graph.gph
        figure9: output/figures/survcurv_skin_died.svg
        figure10: output/figures/survcurv_joint_icuordeath.svg
        figure11: output/figures/joint_graph.gph
        figure12: output/figures/survcurv_joint_died.svg
        figure13: output/figures/survcurv_imid_icuordeath.svg
        figure14: output/figures/imid_graph.gph
        figure15: output/figures/survcurv_imid_died.svg
        figure16: output/figures/survcurv_imiddrugcategory_hospital.svg
        figure17: output/figures/survcurv_bowel_hospital.svg
        figure18: output/figures/survcurv_skin_hospital.svg
        figure19: output/figures/survcurv_joint_hospital.svg
        figure20: output/figures/survcurv_imid_hospital.svg

  run_outcomes_check:
    run: r:latest analysis/outcomes_check_withandwithoutpositivetest.R
    needs: [create_cohorts]
    outputs:
      moderately_sensitive:
        data1: output/data/outcomes_check.csv
  
  run_export_csv:
    run: stata-mp:latest analysis/400_export_csv.do
    needs: [run_cox_models_imid,run_cox_models_joint,run_cox_models_bowel,run_cox_models_skin,run_cox_models_imiddrugcategory,run_cox_models_standtnf,run_cox_models_standtnf3m,run_cox_models_tnfmono,run_cox_models_standil6,run_cox_models_standil17,run_cox_models_standil23,run_cox_models_standjaki,run_cox_models_standritux,run_cox_models_standinflix]
    outputs:
      moderately_sensitive:
        log: logs/export_csv.smcl
        csv_imid: output/data/csv_imid.csv
        csvhaemonc_imid: output/data/csvhaemonc_imid.csv
        csv_joint: output/data/csv_joint.csv
        csvhaemonc_joint: output/data/csvhaemonc_joint.csv
        csv_skin: output/data/csv_skin.csv
        csvhaemonc_skin: output/data/csvhaemonc_skin.csv
        csv_bowel: output/data/csv_bowel.csv
        csvhaemonc_bowel: output/data/csvhaemonc_bowel.csv
        csv_imiddrugcategory: output/data/csv_imiddrugcategory.csv
        csvhaemonc_imiddrugcategory: output/data/csvhaemonc_imiddrugcategory.csv
        csv_standtnf: output/data/csv_standtnf.csv
        csvhaemonc_standtnf: output/data/csvhaemonc_standtnf.csv
        csv_standtnf3m: output/data/csv_standtnf3m.csv
        csvhaemonc_standtnf3m: output/data/csvhaemonc_standtnf3m.csv
        csv_tnfmono: output/data/csv_tnfmono.csv
        csvhaemonc_tnfmono: output/data/csvhaemonc_tnfmono.csv
        csv_standil6: output/data/csv_standil6.csv
        csvhaemonc_standil6: output/data/csvhaemonc_standil6.csv
        csv_standil17: output/data/csv_standil17.csv
        csvhaemonc_standil17: output/data/csvhaemonc_standil17.csv
        csv_standil23: output/data/csv_standil23.csv
        csvhaemonc_standil23: output/data/csvhaemonc_standil23.csv
        csv_standjaki: output/data/csv_standjaki.csv
        csvhaemonc_standjaki: output/data/csvhaemonc_standjaki.csv
        csv_standritux: output/data/csv_standritux.csv
        csvhaemonc_standritux: output/data/csvhaemonc_standritux.csv
        csv_standinflix: output/data/csv_standinflix.csv
        csvhaemonc_standinflix: output/data/csvhaemonc_standinflix.csv

  run_forest_plots:
    run: r:latest analysis/r-immunosuppressant-meds-research/make_forest_plots.R
    needs: [run_export_csv]
    outputs:
      moderately_sensitive:
        merged_csv: output/data/merged_csv_normal.csv
        forest_plot_vs_gen_pop: output/figures/forest_plot_vs_gen_pop.svg
        forest_plot_vs_standard_systemic: output/figures/forest_plot_vs_standard_systemic.svg
